version: '3.7'
services:
  db:
    image: postgres:13-alpine3.14
    command: ["postgres", "-c", "log_statement=all"]
    ports:
      - "5555:5432"
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=pass
    volumes:
      - E:\HW\homeworkTomcat\docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
