###
# Registration
POST https://server.local:8443/api/rest/users/register
Content-Type: application/json

{
  "username": {{$uuid}},
  "password": "top-secret"
}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}

###

POST https://server.local:8443/api/rest/users/login
Content-Type: application/json

{
  "username": "admin",
  "password": "newPass"
}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}

###

GET https://server.local:8443/api/cards.getAll
Authorization: 6NSb+2kcdKF44ut4iBu+dm6YLu6pakWapvxHtxqaPgMr5iRhox/HlhBerAZMILPjwnRtXms+zDfVTLCsao9nuw==

###

GET https://server.local:8443/api/cards.getById=17
Authorization: 6NSb+2kcdKF44ut4iBu+dm6YLu6pakWapvxHtxqaPgMr5iRhox/HlhBerAZMILPjwnRtXms+zDfVTLCsao9nuw==


###

POST https://server.local:8443/api/cards.order
Authorization: 6NSb+2kcdKF44ut4iBu+dm6YLu6pakWapvxHtxqaPgMr5iRhox/HlhBerAZMILPjwnRtXms+zDfVTLCsao9nuw==


###
DELETE https://server.local:8443/api/cards.blockById=1
Authorization: 6NSb+2kcdKF44ut4iBu+dm6YLu6pakWapvxHtxqaPgMr5iRhox/HlhBerAZMILPjwnRtXms+zDfVTLCsao9nuw==


###

POST https://server.local:8443/api/cards.transaction
Authorization: 6NSb+2kcdKF44ut4iBu+dm6YLu6pakWapvxHtxqaPgMr5iRhox/HlhBerAZMILPjwnRtXms+zDfVTLCsao9nuw==
Content-Type: application/json

{
  "fromCardId": 1,
  "toCardId": 2,
  "value": 55
}


###

POST https://server.local:8443/api/rest/users/recovery/getToken
Content-Type: application/json

{
  "login": "admin"
}


###

POST https://server.local:8443/api/rest/users/recovery/setPassword
Content-Type: application/json

{
  "code": "86GPPV",
  "newPassword": "newPass123"
}